use crate::code_generator::to_pascal;
use crate::parser::data::ParsedData;
use quote::{format_ident, quote};

pub fn generate(data: &ParsedData) -> anyhow::Result<String> {
    let variants = data.moves.iter().map(|move_| {
        let ident = format_ident!("{}", to_pascal(move_.identifier.as_str()));
        let id = move_.id;
        quote! { #ident = #id, }
    });

    let tokens = quote! {
        //! AUTO-GENERATED by lemon-pkmn-codegen
        use strum_macros::{Display, EnumIter, FromRepr};

        #[derive(Debug, Copy, Clone, Eq, PartialEq, Hash, EnumIter, Display, FromRepr)]
        #[repr(u16)]
        pub enum MoveId {
            #(#variants)*
        }
    };

    Ok(prettyplease::unparse(&syn::parse2(tokens)?))
}
