use crate::generator::to_pascal;
use crate::parser::data::ParsedData;
use quote::{format_ident, quote};

pub fn generate(data: &ParsedData) -> anyhow::Result<String> {
    let variants = data.moves.iter().map(|move_| {
        let ident = format_ident!("{}", to_pascal(move_.identifier.as_str()));
        let id = move_.id;
        quote! { #ident = #id, }
    });

    let arms = data.moves.iter().map(|m| {
        let ident = format_ident!("{}", to_pascal(&m.identifier));
        let identifier = &m.identifier;
        let pokemon_type = format_ident!("{}", format!("{:?}", m.pokemon_type));
        let power = m.power;
        let pp = m.pp;
        let accuracy = m.accuracy;
        let priority = m.priority;
        let target = format_ident!("{}", format!("{:?}", m.target));
        let damage_class = format_ident!("{}", format!("{:?}", m.damage_class));

        quote! {
            Self::#ident => &MoveData {
                identifier: #identifier,
                pokemon_type: PokemonType::#pokemon_type,
                power: #power,
                pp: #pp,
                accuracy: #accuracy,
                priority: #priority,
                target: MoveTarget::#target,
                damage_class: MoveDamageClass::#damage_class,
            },
        }
    });

    let tokens = quote! {
        //! AUTO-GENERATED by lemon-pkmn-codegen
        use crate::data::MoveData;
        use crate::types::pokemon_type::PokemonType;
        use crate::types::move_target::MoveTarget;
        use crate::types::move_damage_class::MoveDamageClass;
        use strum_macros::{Display, EnumIter};

        #[derive(Debug, Copy, Clone, Eq, PartialEq, Hash, EnumIter, Display)]
        #[repr(u16)]
        pub enum MoveId {
            #(#variants)*
        }

        impl MoveId {
            pub fn data(self) -> &'static MoveData {
                match self {
                    #(#arms)*
                }
            }
        }
    };

    Ok(prettyplease::unparse(&syn::parse2(tokens)?))
}
