use crate::generator::to_pascal;
use crate::parser::data::ParsedData;
use quote::{format_ident, quote};

pub fn generate(data: &ParsedData) -> anyhow::Result<String> {
    let variants = data.species.iter().map(|species| {
        let ident = format_ident!("{}", to_pascal(species.identifier.as_str()));
        let id = species.id;
        quote! { #ident = #id, }
    });

    let arms = data.species.iter().map(|s| {
        let ident = format_ident!("{}", to_pascal(s.identifier.as_str()));
        let identifier = &s.identifier;
        let national_dex = s.national_id;
        let primary_type = format_ident!("{}", format!("{:?}", s.primary_type));
        let secondary_type = match &s.secondary_type {
            Some(t) => {
                let t = format_ident!("{}", format!("{:?}", t));
                quote! { Some(PokemonType::#t) }
            }
            None => quote! { None },
        };
        let (hp, atk, def, sp_atk, sp_def, speed) =
            (s.stats.hp, s.stats.atk, s.stats.def, s.stats.sp_atk, s.stats.sp_def, s.stats.speed);
        let (ev_hp, ev_atk, ev_def, ev_sp_atk, ev_sp_def, ev_speed) =
            (s.ev_yield.hp, s.ev_yield.atk, s.ev_yield.def, s.ev_yield.sp_atk, s.ev_yield.sp_def, s.ev_yield.speed);
        let form_identifier = match &s.form_identifier {
            Some(s) => quote! { Some(#s) },
            None => quote! { None },
        };
        let flags = s.flags.bits();

        quote! {
            Self::#ident => &SpeciesData {
                identifier: #identifier,
                national_dex: #national_dex,
                primary_type: PokemonType::#primary_type,
                secondary_type: #secondary_type,
                base_stats: Stats { hp: #hp, atk: #atk, def: #def, sp_atk: #sp_atk, sp_def: #sp_def, speed: #speed },
                ev_yield: Stats { hp: #ev_hp, atk: #ev_atk, def: #ev_def, sp_atk: #ev_sp_atk, sp_def: #ev_sp_def, speed: #ev_speed },
                form_identifier: #form_identifier,
                flags: #flags,
            },
        }
    });

    let tokens = quote! {
        //! AUTO-GENERATED by lemon-pkmn-codegen
        use crate::data::SpeciesData;
        use crate::types::pokemon_type::PokemonType;
        use crate::types::stats::Stats;
        use strum_macros::{Display, EnumIter};

        #[derive(Debug, Copy, Clone, Eq, PartialEq, Hash, EnumIter, Display)]
        #[repr(u16)]
        pub enum SpeciesId {
            #(#variants)*
        }

        impl SpeciesId {
            pub fn data(self) -> &'static SpeciesData {
                match self {
                    #(#arms)*
                }
            }
        }
    };

    Ok(prettyplease::unparse(&syn::parse2(tokens)?))
}
