use crate::generator::to_pascal;
use crate::parser::data::ParsedData;
use quote::{format_ident, quote};

pub fn generate(data: &ParsedData) -> anyhow::Result<String> {
    let variants = data.species.iter().map(|species| {
        let ident = format_ident!("{}", to_pascal(species.identifier.as_str()));
        let id = species.id;
        quote! { #ident = #id, }
    });

    let arms = data.species.iter().map(|s| {
        let ident = format_ident!("{}", to_pascal(s.identifier.as_str()));
        let identifier = &s.identifier;
        let national_dex = s.national_id;
        let hp = s.stats.hp;
        let atk = s.stats.atk;
        let def = s.stats.def;
        let sp_atk = s.stats.sp_atk;
        let sp_def = s.stats.sp_def;
        let speed = s.stats.speed;
        let is_default_form = s.is_default;
        let is_battle_only = s.is_battle_only;
        let is_mega = s.is_mega;
        let is_gmax = s.is_gmax;

        quote! {
            Self::#ident => &SpeciesData {
                identifier: #identifier,
                national_dex: #national_dex,
                base_stats: Stats { hp: #hp, atk: #atk, def: #def, sp_atk: #sp_atk, sp_def: #sp_def, speed: #speed },
                is_default_form: #is_default_form,
                is_battle_only: #is_battle_only,
                is_mega: #is_mega,
                is_gmax: #is_gmax,
            },
        }
    });

    let tokens = quote! {
        //! AUTO-GENERATED by lemon-pkmn-codegen
        use crate::data::SpeciesData;
        use crate::types::stats::Stats;
        use strum_macros::{Display, EnumIter};

        #[derive(Debug, Copy, Clone, Eq, PartialEq, Hash, EnumIter, Display)]
        #[repr(u16)]
        pub enum SpeciesId {
            #(#variants)*
        }

        impl SpeciesId {
            pub fn data(self) -> &'static SpeciesData {
                match self {
                    #(#arms)*
                }
            }
        }
    };

    Ok(prettyplease::unparse(&syn::parse2(tokens)?))
}
