use strum_macros::{Display, EnumIter, FromRepr};

// ToDo: Auto-generate
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, EnumIter, Display, FromRepr)]
#[repr(u8)]
pub enum Version {
    Red = 1,
    Blue = 2,
    Yellow = 3,
    Gold = 4,
    Silver = 5,
    Crystal = 6,
    Ruby = 7,
    Sapphire = 8,
    Emerald = 9,
    FireRed = 10,
    LeafGreen = 11,
    Diamond = 12,
    Pearl = 13,
    Platinum = 14,
    HeartGold = 15,
    SoulSilver = 16,
    Black = 17,
    White = 18,
    Colosseum = 19,
    Xd = 20,
    Black2 = 21,
    White2 = 22,
    X = 23,
    Y = 24,
    OmegaRuby = 25,
    AlphaSapphire = 26,
    Sun = 27,
    Moon = 28,
    UltraSun = 29,
    UltraMoon = 30,
    LetsGoPikachu = 31,
    LetsgooEevee = 32,
    Sword = 33,
    Shield = 34,
    TheIsleOfArmor = 35,
    TheCrownTundra = 36,
    BrilliantDiamond = 37,
    ShiningPearl = 38,
    LegendsArceus = 39,
    Scarlet = 40,
    Violet = 41,
    TheTealMask = 42,
    TheIndigoDisk = 43,
    RedJapan = 44,
    GreenJapan = 45,
    BlueJapan = 46,
    LegendsZA = 47,
    MegaDimension = 48,
}
